### ISSUE TITLE
Remove member: sujit

### ISSUE THREAD

**Issue by ghost** [Real-Dev-Squad/website-static#59]
cc: @swarajpure  @ankushdharkar @strider99 @ankurnarkhede @whyDontI @sumitd94 

Please eliminate the following folder and/or any outstanding privacy-infringing affiliation of Sujit Mohanty with RDS.

https://github.com/Real-Dev-Squad/website-static/tree/main/members/sujit

**Comment by ankushdharkar** [comment]
DMCA applies on infringement. The original owner uploaded the content themselves.

Since your account looks fake, we will not be taking any action. Please send a PR from original account for removal.
